# 예외 처리

- 실행 도중의 잠재적인 오류까지 검사할 수 없기 때문에 정상적으로 실행이 되다가 비정상적으로 프로그램이 종료되는 경우
    - 운영체제의 문제 (잘못된 시스템 호출의 문제)
    - 입력값의 문제 (존재하지 않는 파일 혹은, 숫자 입력란에 문자 입력 등)
    - 받아들일 수 없는 연산 (0으로 나누기 등)
    - 메모리의 할당 실패 및 부족
    - 컴퓨터 기계 자체의 문제, 논리적 문제가 아닌 물리적 문제가 발생 (전원 문제, 망가진 기억 장치 등)

### 예외를 대비하기 위한 구문
```kotlin
try {
    예외 발생 가능성 있는 문장
} catch (e: 예외 처리 클래스 명) {
    예외를 처리하기 위한 문장
} finally {
    반드시 실행되어야 하는 문장
}
```
> 반드시 실행해야 할 작업이 없다면 `finally` 블록은 생략하고 `try~catch` 블록만으로 코드를 구성할 수 있다.

### 스택의 추적
```kotlin
catch (e : Exception){
    e.printStackTrace()
}
```
`printStackTrace()` 으로 어떤 Exception을 발생시키는 지 정확한 내용을 로그로 확인할 수 있다.

### 예외 처리 특정해서 잡는 이유
```kotlin
try {
    ...
} catch (e: ArithmenticException) {
    e.message
}
```
위 코드에서 예외를 `Exception`을 사용하지 않고 `ArithmenticException` 을 사용하는 이유는 좀 더 예외를 명시적으로 표시하기 위해서이다.

### 특정 조건에 따른 예외 발생
```kotlin
throw Exception(message: String)
```
```kotlin
fun checkAmount(amount: Int) {
    if (amount < 1000) 
        throw Exception("잔고가 $amount 으로 1000 이하")
}
```
강제로 `amount` 값이 1000이하일 때, `Exception` 의 예외를 발생시킨다.